# Generated by Django 3.2 on 2021-06-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_auto_20210602_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vic_no',
            field=models.CharField(max_length=150),
        ),
    ]
